name: Daily Bhavcopy Automation

on:
  schedule:
    - cron: '30 21 * * *'   # 3:00 AM IST
  workflow_dispatch:

jobs:
  run-bhavcopy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas requests gspread google-auth

      - name: Run Bhavcopy
        env:
          GSHEET_CREDS: ${{ secrets.GSHEET_CREDS }}
        run: python bhavcopy.py
